### ISSUE TITLE
Why not in Keras ?

### ISSUE THREAD

**Issue by edmondja** [geffy/tffm#16]
Why don't you make your work compatible with Keras as a simple neural net layer ? 
https://github.com/fchollet/keras/issues/4959

**Comment by geffy** [comment]
Mostly because tffm is a research project focused on FMs
It contains a lot of options which good for experiments and, imo, not suitable for Keras.

I believe it's not a good idea to make all tffm a part of Keras, but it may worth to implement PolyNet or 2-nd order FM as a layer (if not implemented yet)
